name: Bus station CI

on: [push]

jobs:
  bus-station-CI:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ./src
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Check formatting
        run: poetry run tox -e black -- --check
      - name: Check style
        run: poetry run tox -e flake8
      - name: Run unit tests
        run: poetry run tox -e unit_tests
      - name: Run integration tests
        run: poetry run tox -e integration_tests
      - name: Build the package
        run: poetry build
