name: Bus station release

on:
  workflow_dispatch:

jobs:
  bus-station-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup environment
        run: docker-compose up -d
      - name: Build the package
        run: docker-compose run bus-station poetry build
      - name: Bump version and create changelog
        id: cz
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog_increment_filename: body.md
          push: false
      - name: Check if version exists
        uses: mukunku/tag-exists-action@v1.0.0
        id: checkTag
        with:
          tag: ${{ steps.cz.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Fail if tag exists
        if: steps.checkTag.outputs.exists == 'true'
        run: exit 1
      - name: Push new version and changelog
        run: |
          git config --local user.name "Github Action"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add pyproject.toml CHANGELOG.md
          git commit -m "${{ steps.cz.outputs.version }}: Github actions version and changelog update"
          git push
      - name: Publish the package
        run: docker-compose run bus-station poetry publish -u ${{ secrets.PYPI_USER }} -p ${{ secrets.PYPI_PASSWORD }}
      - name: Create github release
        uses: softprops/action-gh-release@v1
        with:
          body_path: "body.md"
          tag_name: ${{ steps.cz.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
